import Head from "next/head";
import { useEffect } from "react";
import * as Tone from "tone";
import styles from "../styles/index.module.css";
import notesArray from "../helpers/notesArray.json";

const setOfNotes = () => {
  return notesArray.map((note) => (
    <div
      key={note.keyBoard}
      id={note.value}
      className={styles.whiteNote}
      onClick={() => onClick(note.value)}
    >
      {note.value}
    </div>
  ));
};

const onClick = (note) => {
  document.getElementById(note).style.backgroundColor = "lightGray";

  const synth = new Tone.PolySynth(Tone.Synth).toDestination();
  const now = Tone.now();
  synth.triggerAttack(note, 0);
  synth.triggerRelease(note, now + 0.5);

  setTimeout(() => {
    document.getElementById(note).style.backgroundColor = "white";
  }, 500);
};

const keyPress = (key) => {
  let typing = notesArray.filter((note) => note.keyBoard === key.key);
  if (typing.length > 0) onClick(typing[0].value);
};

export default function Home() {
  useEffect(() => {
    addEventListener("keypress", keyPress);

    return () => removeEventListener("keypress", keyPress);
  }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Welcome to Web Piano</h1>

        <div className={styles.container}>{setOfNotes()}</div>
      </main>

      <footer>footer</footer>
    </div>
  );
}
